/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MappingProfilesRouteImport } from './routes/mapping-profiles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ValidationErrorsRouteImport } from './routes/validation-errors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingProfilesRoute = MappingProfilesRouteImport.update({
  id: '/mapping-profiles',
  path: '/mapping-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationErrorsRoute = ValidationErrorsRouteImport.update({
  id: '/validation-errors',
  path: '/validation-errors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/mapping-profiles': typeof MappingProfilesRoute
  '/settings': typeof SettingsRoute
  '/validation-errors': typeof ValidationErrorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/mapping-profiles': typeof MappingProfilesRoute
  '/settings': typeof SettingsRoute
  '/validation-errors': typeof ValidationErrorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/mapping-profiles': typeof MappingProfilesRoute
  '/settings': typeof SettingsRoute
  '/validation-errors': typeof ValidationErrorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/logs'
    | '/mapping-profiles'
    | '/settings'
    | '/validation-errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/logs'
    | '/mapping-profiles'
    | '/settings'
    | '/validation-errors'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/logs'
    | '/mapping-profiles'
    | '/settings'
    | '/validation-errors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  MappingProfilesRoute: typeof MappingProfilesRoute
  SettingsRoute: typeof SettingsRoute
  ValidationErrorsRoute: typeof ValidationErrorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping-profiles': {
      id: '/mapping-profiles'
      path: '/mapping-profiles'
      fullPath: '/mapping-profiles'
      preLoaderRoute: typeof MappingProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-errors': {
      id: '/validation-errors'
      path: '/validation-errors'
      fullPath: '/validation-errors'
      preLoaderRoute: typeof ValidationErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  MappingProfilesRoute: MappingProfilesRoute,
  SettingsRoute: SettingsRoute,
  ValidationErrorsRoute: ValidationErrorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
